### ISSUE TITLE
Add delete function

### ISSUE THREAD

**Issue by K-Juno** [K-Juno/capstone-project#11]
**Value Proposition**

As a songwriter I need to have an option to delete my lyrics to be able to discard lyrics I don't want anymore.

**Description**

![userstory06](https://user-images.githubusercontent.com/109735507/193243185-c6f0efd3-0cff-42e2-b189-44062a641915.png)

**Acceptance Criteria**
 - [x] On the Collection page you find delete buttons next to each lyrics title.
 - [x] When you click on a delete button, the respective lyrics title disappears.

**Tasks**
(for developers team)
 - [x] Create delete buttons next to the titles.
 - [x] Write a function that removes the saved lyrics from the database.

**Comment by Murci2022** [comment]
Great job Juno! Looks great to me!
A suggestion from my side:
I think your user story could be even shorter: "As a songwriter I need to have an option to delete my lyrics idear from the list."
