### ISSUE TITLE
Input text in submit form

### ISSUE THREAD

**Issue by K-Juno** [K-Juno/capstone-project#2]
**Value Proposition**

As a songwriter I need to write down lyrics to be able to collect (and not forget) them.

**Description**

![userstory01](https://user-images.githubusercontent.com/109735507/190418706-e2008468-f258-46cd-b5ef-8f1f2bace171.png)

![userstory01 2](https://user-images.githubusercontent.com/109735507/190419861-b7941940-c981-4c41-ac2d-9c2655497bf6.png)

**Acceptance Criteria**
 - [x] When clicking on "Lyrics", you navigate to the page regarding lyrics.
 - [x] On the "Lyrics" page, you can input text content and a title for your new lyrics.
 - [x] When you submit the input data via button click, you get a display of your creation.
 - [x] Whitespace in both input fields will be trimmed and ignored.
 - [x] You get a friendly notification as soon as you try to submit an empty input field.

**Tasks**
(for developers team)
 - [x] Create a feature branch.
 - [x] Create a `h1` for the App name.
 - [x] Create a `nav` called "Lyrics", which is linked to a new page.
 - [x] Create a page for the category "Lyrics".
 - [x] Create a `form` with two required input fields and a submit `button`.
 - [x] Write a submit-function, which renders the input data.
 - [x] Write a logic for trimming whitespace.
 - [x] Set up a notification regarding blank input fields.

**Comment by MerleMak** [comment]
Hi Juni, 
For your Value Proposition you should decide if you want your user to be able to write down or upload data, as both is too much for one User Story.

For the Acceptance Criteria:
You should leave the login part to the side for the first week or two. Try and focus on what happens when you click on the category buttons? Do you need 3 different pages already?, if yes what happens when the user navigated on each page? Maybe you can also include these views into your scribble/wireframe. 
Also, you could use a dummy name to put into your wireframe :)


For the task, (same as Accep.Crit.), the login function takes a long time. You should maybe focus on the display of information first. 
How can your user add Data? Maybe add an input instead of the login? :)

**Comment by K-Juno** [comment]
Thanks for the review, hope the update is sufficient. :)

**Comment by MerleMak** [comment]
Great Job Juni!
