### ISSUE TITLE
Add Subpage with unordered list

### ISSUE THREAD

**Issue by K-Juno** [K-Juno/capstone-project#3]
**Value Proposition**

As a songwriter I need to have my created lyrics gathered in a list to be able to revisit, edit and share them.

**Description**

![userstory02](https://user-images.githubusercontent.com/109735507/190425026-e845912e-3bdd-419f-8cd2-1c8f9e0f1683.png)

**Acceptance Criteria**
 - [x] On the "Lyrics" page, above the lyrics input form, you find a link to your lyrics collection.
 - [x] Following that link, you get a list of all lyrics you've created/inserted so far.
 - [x] Clicking each list item leads to the full content of respective lyrics (same way as when you submit new data in the form).
 - [x] You can return to the submit form anytime.

**Tasks**
(for developers team)
 - [x] Create a feature branch.
 - [x] Create a `header` called "Awesome Collection", which is linked to a new (sub)page.
 - [x] Create a (sub)page for the lyrics collection, which contains a `ul` and `li` for each saved up lyrics.
 - [x] Write a function that renders the input content behind each list item (mapping & state).
 - [x] Create a `nav` element that is linked to the previous page (submit form).

**Comment by asnatschko** [comment]
Sounds great :) Happy Coding :)
