### ISSUE TITLE
Add edit & save buttons/functions

### ISSUE THREAD

**Issue by K-Juno** [K-Juno/capstone-project#4]
**Value Proposition**

As a songwriter I need to have an option to edit my lyrics to be able to make adjustments and to save them after.

**Description**

![userstory03](https://user-images.githubusercontent.com/109735507/190620444-a330d0f5-54a5-4e37-8339-147055f3c369.png)

**Acceptance Criteria**
 - [x] When you have opened one of your existing lyrics, you have edit buttons for each the title and the lyrics.
 - [x] After you have made your corrections, you can save them.
 - [x] Same rules apply here as in the input form: Whitespace will be ignored and empty fields will not be accepted. 

**Tasks**
(for developers team)
 - [x] Create edit buttons next to the title and the lyrics field respectively.
 - [x] Write a function that lets the user rewrite the content in each input field.
 - [x] Write a logic for trimming whitespace.
 - [x] Set up a notification regarding blank input fields.
 - [x] Create a functioning save `button`.

**Comment by DoroVernier** [comment]
Looks great! One question though: Do you still/ again get a friendly notification if you empty one of the fields? If so, do you have to implement this again (I know you have it when creating the lyrics in the first place).

**Comment by K-Juno** [comment]
That is a valid point! I will add that part, thanks for the hint!
