### ISSUE TITLE
Upload files in upload widget

### ISSUE THREAD

**Issue by K-Juno** [K-Juno/capstone-project#5]
**Value Proposition**

As a songwriter/musician I need a way to upload recordings to be able to find, play and share them.

**Description**

![userstory04](https://user-images.githubusercontent.com/109735507/190680647-d8ce7934-d277-4307-912c-081d5f91cdb0.png)

**Acceptance Criteria**
 - [x] When clicking on "Recordings", you navigate to a new page.
 - [x] On the "Recordings" page, you find an upload widget, which allows you to either drag & drop or to browse your local drive.

**Tasks**
(for developers team)
 - [x] Create a `nav` called "Recordings", which is linked to a new page.
 - [x] Add an upload widget (e.g. Cloudinary API).

**Comment by AnH13-6** [comment]
Looks good to me! 🙂
