### ISSUE TITLE
Add Subpage for uploaded files

### ISSUE THREAD

**Issue by K-Juno** [K-Juno/capstone-project#7]
**Value Proposition**

As a songwriter/musician I need one place for my uploaded recordings to be able to find and play them.

**Description**

![userstory05](https://user-images.githubusercontent.com/109735507/191001946-c102ced2-429d-446d-b9ef-bab9d8593379.png)

**Acceptance Criteria**
 - [x] On the "Recordings" page, above the upload widget, you find a link to your recordings.
 - [x] Following that link, you get a list of all uploaded recordings.

**Tasks**
(for developers team)
 - [x] Create a header called "Awesome Collection", which is linked to a new (sub)page.
 - [x] Create a (sub)page for the recordings collection, which stores the uploaded files.
 - [x] Create a nav element that is linked to the previous page (upload widget).

**Comment by DoroVernier** [comment]
Looking good !!! You have my blessings for this userstory.
